---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../red-acre-test
  - ./namespace.yaml
  - ingress.yaml

namespace: red-acre-test-dev
nameSuffix: -dev

patches:
  - target:
      kind: Deployment
      name: backend-deployment
      
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value: 
          - name: FLASK_ENV
            value: development
          - name: FLASK_APP
            value: app.py

  - target:
      kind: Deployment
      name: frontend-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0
        value: 
          name: REACT_APP_BACKEND_HOST
          value: red-acre-test-dev.com

      - op: add
        path: /spec/template/spec/containers/0/env/2
        value: 
          name: NODE_ENV
          value: development
      
      
        
          
    