{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "red-acre-test-chart.serviceAccountName" . }}
  labels:
    {{- include "red-acre-test-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

git remote add origin git@github.com:renemifsud/test-project-ra.git
git branch -M master
git push -u origin master